### ISSUE TITLE
Reconsider introduction of advanced `wildcards.` qualifier usage in episode 4

### ISSUE THREAD

**Issue by sdruskat** [carpentries-incubator/workflows-snakemake#93]
In Episode 4 there is [a callout](https://github.com/carpentries-incubator/workflows-snakemake/blob/7f954ca15e81f219edbb4d7c1154f0bcb78f77c4/_episodes/04-patterns.md?plain=1#L89-L93) which seemed unclear *to me* on reading, and it took more time to understand than it could have:

> Our arbitrary wildcards like `{book}` can only be used in `input:` and `output:` fields. They cannot be used directly in actions. If you need to refer to the current value of a wildcard in an action you need to qualify it with `wildcards.`. For example: `{wildcards.file}`.

I think the confusion arose from the fact that just before that callout, we *did* use `book` in the action, albeit with the `input.` namespace/qualifier. Also, the "native" `wildcards.` qualifier is mentioned here for the first time. 

I guess the respective section in the Snakemake docs is this one: https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#wildcards. Reading this section, I'm wondering whether mentioning `wildcards.` is helpful here at all. This is because a new (or advanced) *concept* is introduced here without further explanation, that of wildcard resolution from dependencies of other rules, e.g., a `rule2` depending on `101/file.A.txt`, which resolves a `rule1` to produce the file, e.g.

```yaml
# rule1
rule complex_conversion:
    input:
        "{dataset}/inputfile"
    output:
        "{dataset}/file.{group}.txt"
    shell:
        "somecommand --group {wildcards.group} < {input} > {output}"
```

I think that the examples that are gone through in the episode up to the callout are clear enough the explain the more basic concept used here (i.e., using the keys for inputs as placeholders), and that perhaps the above use of `{wildcards.<x>}` could be wrapped in a "If you want to learn more about how wildcards can be used to automatically resolve rule inputs and outputs, read the docs" or similar?
